CREATE TABLE flavorlogs_logs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    info TEXT NOT NULL,
    ordered TEXT NOT NULL,
    rating INTEGER,
    date TEXT NOT NULL,
    image_link TEXT,
    eatery_id INTEGER
        REFERENCES flavorlogs_eateries(id) ON DELETE CASCADE NOT NULL
);
